# Checks security, runs unit tests, and publishes a composer package
# See https://git.luminfire.net/templates/gitlab/ci-templates/-/tree/master/composer-package
#
# See also:
# - https://docs.gitlab.com/ee/user/packages/
# - https://docs.gitlab.com/13.2/ee/user/packages/composer_repository/index.html
# - https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Composer.gitlab-ci.yml

stages:
  - solcare
  - test
  - build
  - deploy
  - release

variables:
  CLOUDFLARE_PAGES_PROJECT_NAME: betteruptime-laravel
  # CLOUDFLARE_API_TOKEN: # add to GitLab CI/CD variable

include:
  - project: 'templates/gitlab/ci-templates'
    file:
      - 'presets/php.yml'
      - 'test/phpunit.yml'
      - 'build/composer-package.yml'
      - 'deploy/documentation/brilliantsolutions-cloudflare-pages.yml'
